import {React, useState} from 'react'
import Select from 'react-select'
import './Ingredients.css'
import { useNavigate } from "react-router-dom";


const options = [
    { value: 'salt', label: 'salt' },
    { value: 'olive oil', label: 'olive oil' },
    { value: 'butter', label: 'butter' },
    { value: 'sugar', label: 'sugar' },
    { value: 'water', label: 'water' },
    { value: 'flour', label: 'flour' },
    { value: 'garlic', label: 'garlic' },
    { value: 'eggs', label: 'eggs' },
    { value: 'onion', label: 'onion' },
    { value: 'vanilla extract', label: 'vanilla extract' },
    { value: 'milk', label: 'milk' },
    { value: 'kosher salt', label: 'kosher salt' },
    { value: 'lemon juice', label: 'lemon juice' },
    { value: 'unsalted butter', label: 'unsalted butter' },
    { value: 'black pepper', label: 'black pepper' },
    { value: 'baking powder', label: 'baking powder' },
    { value: 'pepper', label: 'pepper' },
    { value: 'salt and pepper', label: 'salt and pepper' },
    { value: 'egg', label: 'egg' },
    { value: 'brown sugar', label: 'brown sugar' },
    { value: 'baking soda', label: 'baking soda' },
    { value: 'garlic cloves', label: 'garlic cloves' },
    { value: 'vegetable oil', label: 'vegetable oil' },
    { value: 'granulated sugar', label: 'granulated sugar' },
    { value: 'honey', label: 'honey' },
    { value: 'ground cinnamon', label: 'ground cinnamon' },
    { value: 'ground pepper', label: 'ground pepper' },
    { value: 'cream cheese', label: 'cream cheese' },
    { value: 'parmesan cheese', label: 'parmesan cheese' },
    { value: 'garlic powder', label: 'garlic powder' },
    { value: 'carrots', label: 'carrots' },
    { value: 'cinnamon', label: 'cinnamon' },
    { value: 'oregano', label: 'oregano' },
    { value: 'red onion', label: 'red onion' },
    { value: 'heavy cream', label: 'heavy cream' },
    { value: 'celery', label: 'celery' },
    { value: 'chicken', label: 'chicken' },
    { value: 'sour cream', label: 'sour cream' },
    { value: 'vanilla', label: 'vanilla' },
    { value: 'sea salt', label: 'sea salt' },
    { value: 'green onions', label: 'green onions' },
    { value: 'lime juice', label: 'lime juice' },
    { value: 'soy sauce', label: 'soy sauce' },
    { value: 'powdered sugar', label: 'powdered sugar' },
    { value: 'fresh parsley', label: 'fresh parsley' },
    { value: 'bacon', label: 'bacon' },
    { value: 'cornstarch', label: 'cornstarch' },
    { value: 'ground cumin', label: 'ground cumin' },
    { value: 'tomatoes', label: 'tomatoes' },
    { value: 'canola oil', label: 'canola oil' },
    { value: 'oil', label: 'oil' },
    { value: 'chicken broth', label: 'chicken broth' },
    { value: 'maple syrup', label: 'maple syrup' },
    { value: 'red bell pepper', label: 'red bell pepper' },
    { value: 'canned tomatoes', label: 'canned tomatoes' },
    { value: 'lemon zest', label: 'lemon zest' },
    { value: 'paprika', label: 'paprika' },
    { value: 'dijon mustard', label: 'dijon mustard' },
    { value: 'chili powder', label: 'chili powder' },
    { value: 'chocolate', label: 'chocolate' },
    { value: 'mayonnaise', label: 'mayonnaise' },
    { value: 'white sugar', label: 'white sugar' },
    { value: 'onions', label: 'onions' },
    { value: 'fresh cilantro', label: 'fresh cilantro' },
    { value: 'parsley', label: 'parsley' },
    { value: 'cilantro', label: 'cilantro' },
    { value: 'pecans', label: 'pecans' },
    { value: 'beef', label: 'beef' },
    { value: 'ginger', label: 'ginger' },
    { value: 'garlic clove', label: 'garlic clove' },
    { value: 'red pepper flakes', label: 'red pepper flakes' },
    { value: 'walnuts', label: 'walnuts' },
    { value: 'cayenne pepper', label: 'cayenne pepper' },
    { value: 'extra virgin olive oil', label: 'extra virgin olive oil' },
    { value: 'carrot', label: 'carrot' },
    { value: 'coconut oil', label: 'coconut oil' },
    { value: 'zucchini', label: 'zucchini' },
    { value: 'strawberries', label: 'strawberries' },
    { value: 'worcestershire sauce', label: 'worcestershire sauce' },
    { value: 'sesame oil', label: 'sesame oil' },
    { value: 'food dye', label: 'food dye' },
    { value: 'orange juice', label: 'orange juice' },
    { value: 'potatoes', label: 'potatoes' },
    { value: 'fish', label: 'fish' },
    { value: 'tomato', label: 'tomato' },
    { value: 'juice of lemon', label: 'juice of lemon' },
    { value: 'avocado', label: 'avocado' },
    { value: 'buttermilk', label: 'buttermilk' },
    { value: 'light brown sugar', label: 'light brown sugar' },
    { value: 'nutmeg', label: 'nutmeg' },
    { value: 'balsamic vinegar', label: 'balsamic vinegar' },
    { value: 'ground ginger', label: 'ground ginger' },
    { value: 'yellow onion', label: 'yellow onion' },
    { value: 'fresh ginger', label: 'fresh ginger' },
    { value: 'egg whites', label: 'egg whites' },
    { value: 'ground nutmeg', label: 'ground nutmeg' },
    { value: 'shredded cheddar cheese', label: 'shredded cheddar cheese' },
    { value: 'green bell pepper', label: 'green bell pepper' },
    { value: 'almonds', label: 'almonds' },
    { value: 'whole milk', label: 'whole milk' },
    { value: 'lemon', label: 'lemon' },
    { value: 'shrimp', label: 'shrimp' },
    { value: 'tomato paste', label: 'tomato paste' },
    { value: 'scallions', label: 'scallions' },
    { value: 'onion powder', label: 'onion powder' },
    { value: 'all purpose flour', label: 'all purpose flour' },
    { value: 'chicken stock', label: 'chicken stock' },
    { value: 'egg yolks', label: 'egg yolks' },
    { value: 'cumin', label: 'cumin' },
    { value: 'red wine vinegar', label: 'red wine vinegar' },
    { value: 'confectioners sugar', label: 'confectioners sugar' },
    { value: 'shallots', label: 'shallots' },
    { value: 'fresh basil', label: 'fresh basil' },
    { value: 'ground beef', label: 'ground beef' },
    { value: 'spinach', label: 'spinach' },
    { value: 'mushrooms', label: 'mushrooms' },
    { value: 'blueberries', label: 'blueberries' },
    { value: 'rye meal', label: 'rye meal' },
    { value: 'fresh thyme', label: 'fresh thyme' },
    { value: 'bread', label: 'bread' },
    { value: 'peanut butter', label: 'peanut butter' },
    { value: 'dried thyme', label: 'dried thyme' },
    { value: 'skinless boneless chicken breasts', label: 'skinless boneless chicken breasts' },
    { value: 'juice of lime', label: 'juice of lime' },
    { value: 'bananas', label: 'bananas' },
    { value: 'cucumber', label: 'cucumber' },
    { value: 'banana', label: 'banana' },
    { value: 'cherry tomatoes', label: 'cherry tomatoes' },
    { value: 'coconut', label: 'coconut' },
    { value: 'heavy whipping cream', label: 'heavy whipping cream' },
    { value: 'Salt & Pepper', label: 'Salt & Pepper' },
    { value: 'apple cider vinegar', label: 'apple cider vinegar' },
    { value: 'bay leaf', label: 'bay leaf' },
    { value: 'bay leaves', label: 'bay leaves' },
    { value: 'sea-salt', label: 'sea-salt' },
    { value: 'chocolate chips', label: 'chocolate chips' },
    { value: 'parmesan', label: 'parmesan' },
    { value: 'cocoa powder', label: 'cocoa powder' },
    { value: 'ketchup', label: 'ketchup' },
    { value: 'shallot', label: 'shallot' },
    { value: 'dry white wine', label: 'dry white wine' },
    { value: 'orange zest', label: 'orange zest' },
    { value: 'sesame seeds', label: 'sesame seeds' },
    { value: 'salsa', label: 'salsa' },
    { value: 'feta cheese', label: 'feta cheese' },
    { value: 'raisins', label: 'raisins' },
    { value: 'vegetable broth', label: 'vegetable broth' },
    { value: 'pasta', label: 'pasta' },
    { value: 'apple', label: 'apple' },
    { value: 'apples', label: 'apples' },
    { value: 'unsweetened cocoa powder', label: 'unsweetened cocoa powder' },
    { value: 'peas', label: 'peas' },
    { value: 'rice', label: 'rice' },
    { value: 'broccoli', label: 'broccoli' },
    { value: 'ground cloves', label: 'ground cloves' },
    { value: 'cream', label: 'cream' },
    { value: 'raspberries', label: 'raspberries' },
    { value: 'almond milk', label: 'almond milk' },
    { value: 'basil', label: 'basil' },
    { value: 'thyme', label: 'thyme' },
    { value: 'hot sauce', label: 'hot sauce' },
    { value: 'green onion', label: 'green onion' },
    { value: 'dried basil', label: 'dried basil' },
    { value: 'sweet potatoes', label: 'sweet potatoes' },
    { value: 'active yeast', label: 'active yeast' },
    { value: 'kale', label: 'kale' },
    { value: 'cheddar cheese', label: 'cheddar cheese' },
    { value: 'cooking oil', label: 'cooking oil' },
    { value: 'fresh rosemary', label: 'fresh rosemary' },
    { value: 'basil leaves', label: 'basil leaves' },
    { value: 'canned black beans', label: 'canned black beans' },
    { value: 'curry powder', label: 'curry powder' },
    { value: 'bbq sauce', label: 'bbq sauce' },
    { value: 'almond extract', label: 'almond extract' },
    { value: 'cauliflower', label: 'cauliflower' },
    { value: 'jalapeno', label: 'jalapeno' },
    { value: 'chicken breasts', label: 'chicken breasts' },
    { value: 'coarse salt', label: 'coarse salt' },
    { value: 'asparagus', label: 'asparagus' },
    { value: 'whipping cream', label: 'whipping cream' },
    { value: 'italian seasoning', label: 'italian seasoning' },
    { value: 'chives', label: 'chives' },
    { value: 'low sodium chicken broth', label: 'low sodium chicken broth' },
    { value: 'cider vinegar', label: 'cider vinegar' },
    { value: 'corn syrup', label: 'corn syrup' },
    { value: 'rice vinegar', label: 'rice vinegar' },
    { value: 'smoked paprika', label: 'smoked paprika' },
    { value: 'quinoa', label: 'quinoa' },
    { value: 'semisweet chocolate chips', label: 'semisweet chocolate chips' },
    { value: 'goat cheese', label: 'goat cheese' },
    { value: 'pineapple', label: 'pineapple' },
    { value: 'ham', label: 'ham' },
    { value: 'lime', label: 'lime' },
    { value: 'ice', label: 'ice' },
    { value: 'cumin seeds', label: 'cumin seeds' },
    { value: 'shredded mozzarella cheese', label: 'shredded mozzarella cheese' },
    { value: 'capers', label: 'capers' },
    { value: 'low sodium soy sauce', label: 'low sodium soy sauce' },
    { value: 'shortening', label: 'shortening' },
    { value: 'dark brown sugar', label: 'dark brown sugar' },
    { value: 'sharp cheddar cheese', label: 'sharp cheddar cheese' },
    { value: 'fat-free milk', label: 'fat-free milk' },
    { value: 'baby spinach', label: 'baby spinach' },
    { value: 'cabbage', label: 'cabbage' },
    { value: 'coconut milk', label: 'coconut milk' },
    { value: 'white wine', label: 'white wine' },
    { value: 'butternut squash', label: 'butternut squash' },
    { value: 'whole wheat flour', label: 'whole wheat flour' },
    { value: 'mango', label: 'mango' },
    { value: 'bread crumbs', label: 'bread crumbs' },
    { value: 'rolled oats', label: 'rolled oats' },
    { value: 'fresh basil leaves', label: 'fresh basil leaves' },
    { value: 'ground coriander', label: 'ground coriander' },
    { value: 'egg yolk', label: 'egg yolk' },
    { value: 'white wine vinegar', label: 'white wine vinegar' },
    { value: 'whipped topping', label: 'whipped topping' },
    { value: 'flour tortillas', label: 'flour tortillas' },
    { value: 'orange', label: 'orange' },
    { value: 'mustard', label: 'mustard' },
    { value: 'molasses', label: 'molasses' },
    { value: 'green beans', label: 'green beans' },
    { value: 'creamy peanut butter', label: 'creamy peanut butter' },
    { value: 'dried cranberries', label: 'dried cranberries' },
    { value: 'greek yogurt', label: 'greek yogurt' },
    { value: 'sweet potato', label: 'sweet potato' },
    { value: 'sweetened condensed milk', label: 'sweetened condensed milk' },
    { value: 'peaches', label: 'peaches' },
    { value: 'fresh chives', label: 'fresh chives' },
    { value: 'pine nuts', label: 'pine nuts' },
    { value: 'white vinegar', label: 'white vinegar' },
    { value: 'rosemary', label: 'rosemary' },
    { value: 'cranberries', label: 'cranberries' },
    { value: 'skinless boneless chicken breast halves', label: 'skinless boneless chicken breast halves' },
    { value: 'pumpkin pie spice', label: 'pumpkin pie spice' },
    { value: 'marshmallows', label: 'marshmallows' },
    { value: 'fresh mushrooms', label: 'fresh mushrooms' },
    { value: 'bell pepper', label: 'bell pepper' },
    { value: 'broccoli florets', label: 'broccoli florets' },
    { value: 'fresh dill', label: 'fresh dill' },
    { value: 'white onion', label: 'white onion' },
    { value: 'canned tomato sauce', label: 'canned tomato sauce' },
    { value: 'egg white', label: 'egg white' },
    { value: 'coriander', label: 'coriander' },
    { value: 'lettuce', label: 'lettuce' },
    { value: 'chicken breast', label: 'chicken breast' },
    { value: 'fresh mint', label: 'fresh mint' },
    { value: 'almond flour', label: 'almond flour' },
    { value: 'margarine', label: 'margarine' },
    { value: 'pumpkin puree', label: 'pumpkin puree' },
    { value: 'lime zest', label: 'lime zest' },
    { value: 'tomato sauce', label: 'tomato sauce' },
    { value: 'lean ground beef', label: 'lean ground beef' },
    { value: 'garlic salt', label: 'garlic salt' },
    { value: 'jalapeno pepper', label: 'jalapeno pepper' },
    { value: 'semi sweet chocolate chips', label: 'semi sweet chocolate chips' },
    { value: 'cayenne', label: 'cayenne' },
    { value: 'mint', label: 'mint' },
    { value: 'turmeric', label: 'turmeric' },
    { value: 'turkey', label: 'turkey' },
    { value: 'vegetable stock', label: 'vegetable stock' },
    { value: 'evaporated milk', label: 'evaporated milk' },
    { value: 'wine', label: 'wine' },
    { value: 'beef broth', label: 'beef broth' },
    { value: 'avocados', label: 'avocados' },
    { value: 'cookies', label: 'cookies' },
    { value: 'fish sauce', label: 'fish sauce' },
    { value: 'healthy request cream of celery soup', label: 'healthy request cream of celery soup' },
    { value: 'monterey jack cheese', label: 'monterey jack cheese' },
    { value: 'corn tortillas', label: 'corn tortillas' },
    { value: 'sweet onion', label: 'sweet onion' },
    { value: 'whipped cream', label: 'whipped cream' },
    { value: 'ground allspice', label: 'ground allspice' },
    { value: 'grape tomatoes', label: 'grape tomatoes' },
    { value: 'cake flour', label: 'cake flour' },
    { value: 'vanilla ice cream', label: 'vanilla ice cream' },
    { value: 'crushed red pepper', label: 'crushed red pepper' },
    { value: 'turmeric powder', label: 'turmeric powder' },
    { value: 'half & half', label: 'half & half' },
    { value: 'coconut flour', label: 'coconut flour' },
    { value: 'vodka', label: 'vodka' },
    { value: 'olives', label: 'olives' },
    { value: 'garam masala', label: 'garam masala' },
    { value: 'vinegar', label: 'vinegar' },
    { value: 'swiss cheese', label: 'swiss cheese' },
    { value: 'mozzarella cheese', label: 'mozzarella cheese' },
    { value: 'cream of tartar', label: 'cream of tartar' },
    { value: 'oats', label: 'oats' },
    { value: 'rib tips', label: 'rib tips' },
    { value: 'pepper sauce', label: 'pepper sauce' },
    { value: 'salted butter', label: 'salted butter' },
    { value: 'pumpkin', label: 'pumpkin' },
    { value: 'plum tomatoes', label: 'plum tomatoes' },
    { value: 'red potatoes', label: 'red potatoes' },
    { value: 'beer', label: 'beer' },
    { value: 'pork', label: 'pork' },
    { value: 'yellow bell pepper', label: 'yellow bell pepper' },
    { value: 'dates', label: 'dates' },
    { value: 'chilli powder', label: 'chilli powder' },
    { value: 'salad mix', label: 'salad mix' },
    { value: 'ice cubes', label: 'ice cubes' },
    { value: 'corn', label: 'corn' },
    { value: 'mint leaves', label: 'mint leaves' },
    { value: 'black peppercorns', label: 'black peppercorns' },
    { value: 'potato', label: 'potato' },
    { value: 'fresh flat-leaf parsley', label: 'fresh flat-leaf parsley' },
    { value: 'pie crust', label: 'pie crust' },
    { value: 'vanilla bean', label: 'vanilla bean' },
    { value: 'yogurt', label: 'yogurt' },
    { value: 'salmon', label: 'salmon' },
    { value: 'fruit', label: 'fruit' },
    { value: 'bittersweet chocolate', label: 'bittersweet chocolate' },
    { value: 'white pepper', label: 'white pepper' },
    { value: 'breadcrumbs', label: 'breadcrumbs' },
    { value: 'black olives', label: 'black olives' },
    { value: 'cheese', label: 'cheese' },
    { value: 'cornmeal', label: 'cornmeal' },
    { value: 'cooked rice', label: 'cooked rice' },
    { value: 'fresh thyme leaves', label: 'fresh thyme leaves' },
    { value: 'pineapple juice', label: 'pineapple juice' },
    { value: 'real bacon recipe pieces', label: 'real bacon recipe pieces' },
    { value: 'chia seeds', label: 'chia seeds' },
    { value: 'cherries', label: 'cherries' },
    { value: 'eggplant', label: 'eggplant' },
    { value: 'lemon peel', label: 'lemon peel' },
    { value: 'nuts', label: 'nuts' },
    { value: 'russet potatoes', label: 'russet potatoes' },
    { value: 'plain flour', label: 'plain flour' },
    { value: 'coconut sugar', label: 'coconut sugar' },
    { value: 'leeks', label: 'leeks' },
    { value: 'cilantro leaves', label: 'cilantro leaves' },
    { value: 'low fat milk', label: 'low fat milk' },
    { value: 'red wine', label: 'red wine' },
    { value: 'cinnamon stick', label: 'cinnamon stick' },
    { value: 'romaine lettuce', label: 'romaine lettuce' },
    { value: 'brussels sprouts', label: 'brussels sprouts' },
    { value: 'coffee', label: 'coffee' },
    { value: 'ground turkey', label: 'ground turkey' },
    { value: 'kalamata olives', label: 'kalamata olives' },
    { value: 'bread flour', label: 'bread flour' },
    { value: 'dark chocolate', label: 'dark chocolate' },
    { value: 'dried parsley', label: 'dried parsley' },
    { value: 'ricotta cheese', label: 'ricotta cheese' },
    { value: 'ice cream', label: 'ice cream' },
    { value: 'graham cracker crumbs', label: 'graham cracker crumbs' },
    { value: 'semisweet chocolate', label: 'semisweet chocolate' },
    { value: 'gelatin', label: 'gelatin' },
    { value: 'ghee', label: 'ghee' },
    { value: 'puff pastry', label: 'puff pastry' },
    { value: 'canned chickpeas', label: 'canned chickpeas' },
    { value: 'club soda', label: 'club soda' },
    { value: 'peanut oil', label: 'peanut oil' },
    { value: 'black beans', label: 'black beans' },
    { value: 'fresh mint leaves', label: 'fresh mint leaves' },
    { value: 'arugula', label: 'arugula' },
    { value: 'slivered almonds', label: 'slivered almonds' },
    { value: 'breakfast links', label: 'breakfast links' },
    { value: 'brown rice', label: 'brown rice' },
    { value: 'spaghetti', label: 'spaghetti' },
    { value: 'horseradish', label: 'horseradish' },
    { value: 'fresh cilantro leaves', label: 'fresh cilantro leaves' },
    { value: 'plain greek yogurt', label: 'plain greek yogurt' },
    { value: 'apple cider', label: 'apple cider' },
    { value: 'peanuts', label: 'peanuts' },
    { value: 'radishes', label: 'radishes' },
    { value: 'barbecue sauce', label: 'barbecue sauce' },
    { value: 'unbleached flour', label: 'unbleached flour' },
    { value: 'tofu', label: 'tofu' },
    { value: 'tahini', label: 'tahini' },
    { value: 'blue cheese', label: 'blue cheese' },
    { value: 'dry mustard', label: 'dry mustard' },
    { value: 'roma tomatoes', label: 'roma tomatoes' },
    { value: 'plain yogurt', label: 'plain yogurt' },
    { value: 'apple juice', label: 'apple juice' },
    { value: 'dill', label: 'dill' },
    { value: 'rum', label: 'rum' },
    { value: 'almond butter', label: 'almond butter' },
    { value: 'corn kernels', label: 'corn kernels' },
    { value: 'red pepper', label: 'red pepper' },
    { value: 'bourbon', label: 'bourbon' },
    { value: 'artichoke hearts', label: 'artichoke hearts' },
    { value: 'ground pork', label: 'ground pork' },
    { value: 'mustard seeds', label: 'mustard seeds' },
    { value: 'lemons', label: 'lemons' },
    { value: 'blackberries', label: 'blackberries' },
    { value: 'celery stalks', label: 'celery stalks' },
    { value: 'red onions', label: 'red onions' },
    { value: 'rice wine vinegar', label: 'rice wine vinegar' },
    { value: 'pork chops', label: 'pork chops' },
    { value: 'red bell peppers', label: 'red bell peppers' },
    { value: 'deep dish pie crust', label: 'deep dish pie crust' },
    { value: 'yukon gold potatoes', label: 'yukon gold potatoes' },
    { value: 'golden raisins', label: 'golden raisins' },
    { value: 'skinless boneless chicken thighs', label: 'skinless boneless chicken thighs' },
    { value: 'frozen corn', label: 'frozen corn' },
    { value: 'yeast', label: 'yeast' },
    { value: 'white chocolate chips', label: 'white chocolate chips' },
    { value: 'pistachios', label: 'pistachios' },
    { value: 'cooked quinoa', label: 'cooked quinoa' },
    { value: 'marinara sauce', label: 'marinara sauce' },
    { value: 'hazelnuts', label: 'hazelnuts' },
    { value: 'cashews', label: 'cashews' },
    { value: 'leek', label: 'leek' },
    { value: 'orange peel', label: 'orange peel' },
    { value: 'jalapenos', label: 'jalapenos' },
    { value: 'fennel seeds', label: 'fennel seeds' },
    { value: 'green pepper', label: 'green pepper' },
    { value: 'dried rosemary', label: 'dried rosemary' },
    { value: 'white rice', label: 'white rice' },
    { value: 'ground turmeric', label: 'ground turmeric' },
    { value: 'summer savory', label: 'summer savory' },
    { value: 'skinless boneless chicken breast', label: 'skinless boneless chicken breast' },
    { value: 'lime wedges', label: 'lime wedges' },
    { value: 'prosciutto', label: 'prosciutto' },
    { value: 'tortilla chips', label: 'tortilla chips' },
    { value: 'cucumbers', label: 'cucumbers' },
    { value: 'panko bread crumbs', label: 'panko bread crumbs' },
    { value: 'simple syrup', label: 'simple syrup' },
    { value: 'jalapeno peppers', label: 'jalapeno peppers' },
    { value: 'pecan', label: 'pecan' },
    { value: 'sprinkles', label: 'sprinkles' },
    { value: 'spring onions', label: 'spring onions' },
    { value: 'creme fraiche', label: 'creme fraiche' },
    { value: 'curry leaves', label: 'curry leaves' },
    { value: 'kitchen bouquet', label: 'kitchen bouquet' },
    { value: 'taco seasoning', label: 'taco seasoning' },
    { value: 'brandy', label: 'brandy' },
    { value: 'sausage', label: 'sausage' },
    { value: 'cooked chicken', label: 'cooked chicken' },
    { value: 'canned pumpkin', label: 'canned pumpkin' },
    { value: 'seasoned salt', label: 'seasoned salt' },
    { value: 'pears', label: 'pears' },
    { value: 'quick cooking oats', label: 'quick cooking oats' },
    { value: 'half and half', label: 'half and half' },
    { value: 'agave nectar', label: 'agave nectar' },
    { value: 'poppy seeds', label: 'poppy seeds' },
    { value: 'green chillies', label: 'green chillies' },
    { value: 'allspice', label: 'allspice' },
    { value: 'bell peppers', label: 'bell peppers' },
    { value: 'fresh sage', label: 'fresh sage' },
    { value: 'stevia', label: 'stevia' },
    { value: 'ground cardamom', label: 'ground cardamom' },
    { value: 'flat-leaf parsley', label: 'flat-leaf parsley' },
    { value: 'tequila', label: 'tequila' },
    { value: 'fresh parsley leaves', label: 'fresh parsley leaves' },
    { value: 'chickpeas', label: 'chickpeas' },
    { value: 'hoisin sauce', label: 'hoisin sauce' },
    { value: 'sriracha', label: 'sriracha' },
    { value: 'roasted red peppers', label: 'roasted red peppers' },
    { value: 'yellow onions', label: 'yellow onions' },
    { value: 'corn starch', label: 'corn starch' },
    { value: 'green chilies', label: 'green chilies' },
    { value: 'skim milk', label: 'skim milk' },
    { value: 'coriander seeds', label: 'coriander seeds' },
    { value: 'cocoa', label: 'cocoa' },
    { value: 'leafy vegetables', label: 'leafy vegetables' },
    { value: 'table salt', label: 'table salt' },
    { value: 'pesto', label: 'pesto' },
    { value: 'beef stock', label: 'beef stock' },
    { value: 'peppers', label: 'peppers' },
    { value: 'dry red wine', label: 'dry red wine' },
    { value: 'chili sauce', label: 'chili sauce' },
    { value: 'fennel bulb', label: 'fennel bulb' },
    { value: 'button mushrooms', label: 'button mushrooms' },
    { value: 'salmon fillets', label: 'salmon fillets' },
    { value: 'graham crackers', label: 'graham crackers' },
    { value: 'granny smith apples', label: 'granny smith apples' },
    { value: 'lemon rind', label: 'lemon rind' },
    { value: 'dark chocolate chips', label: 'dark chocolate chips' },
    { value: 'berries', label: 'berries' },
    { value: 'unsweetened applesauce', label: 'unsweetened applesauce' },
    { value: 'mayo', label: 'mayo' },
    { value: 'canned coconut milk', label: 'canned coconut milk' },
    { value: 'applesauce', label: 'applesauce' },
    { value: 'nutritional yeast', label: 'nutritional yeast' },
    { value: 'thyme sprigs', label: 'thyme sprigs' },
    { value: 'hamburger buns', label: 'hamburger buns' },
    { value: 'baking mix', label: 'baking mix' },
    { value: 'baguette', label: 'baguette' },
    { value: 'frozen spinach', label: 'frozen spinach' },
    { value: 'ears corn', label: 'ears corn' },
    { value: 'rhubarb', label: 'rhubarb' },
    { value: 'white cake mix', label: 'white cake mix' },
    { value: 'part-skim mozzarella cheese', label: 'part-skim mozzarella cheese' },
    { value: 'icing sugar', label: 'icing sugar' },
    { value: 'white chocolate', label: 'white chocolate' },
    { value: 'roasted garlic', label: 'roasted garlic' },
    { value: 'pear', label: 'pear' },
    { value: 'seasoning', label: 'seasoning' },
    { value: 'red cabbage', label: 'red cabbage' },
    { value: 'lemon wedges', label: 'lemon wedges' },
    { value: 'beets', label: 'beets' },
    { value: 'limes', label: 'limes' },
    { value: 'feta', label: 'feta' },
    { value: 'shredded chicken', label: 'shredded chicken' },
    { value: 'ice water', label: 'ice water' },
    { value: 'liquid smoke', label: 'liquid smoke' },
    { value: 'sherry vinegar', label: 'sherry vinegar' },
    { value: 'watermelon', label: 'watermelon' },
    { value: 'thyme leaves', label: 'thyme leaves' },
    { value: 'nonfat cool whip', label: 'nonfat cool whip' },
    { value: 'cream of chicken soup', label: 'cream of chicken soup' },
    { value: 'cinnamon sticks', label: 'cinnamon sticks' },
    { value: 'oranges', label: 'oranges' },
    { value: 'flat leaf parsley', label: 'flat leaf parsley' },
    { value: 'ground mustard', label: 'ground mustard' },
    { value: 'peach', label: 'peach' },
    { value: 'sunflower seeds', label: 'sunflower seeds' },
    { value: 'pepperoni', label: 'pepperoni' },
    { value: 'tomato puree', label: 'tomato puree' },
    { value: 'provolone cheese', label: 'provolone cheese' },
    { value: 'canned diced tomatoes', label: 'canned diced tomatoes' },
    { value: 'scallion', label: 'scallion' },
    { value: 'canned pineapple', label: 'canned pineapple' },
    { value: 'pita breads', label: 'pita breads' },
    { value: 'vegetable shortening', label: 'vegetable shortening' },
    { value: 'food coloring', label: 'food coloring' },
    { value: 'parsley leaves', label: 'parsley leaves' },
    { value: 'canned pumpkin puree', label: 'canned pumpkin puree' },
    { value: 'canned kidney beans', label: 'canned kidney beans' },
    { value: 'pot roast', label: 'pot roast' },
    { value: 'french bread', label: 'french bread' },
    { value: 'mushroom', label: 'mushroom' },
    { value: 'pancetta', label: 'pancetta' },
    { value: 'yellow cornmeal', label: 'yellow cornmeal' },
    { value: 'english cucumber', label: 'english cucumber' },
    { value: 'pork tenderloin', label: 'pork tenderloin' },
    { value: 'unsweetened chocolate', label: 'unsweetened chocolate' },
    { value: 'chili', label: 'chili' },
    { value: 'pizza sauce', label: 'pizza sauce' },
    { value: 'unsweetened shredded coconut', label: 'unsweetened shredded coconut' },
    { value: 'xanthan gum', label: 'xanthan gum' },
    { value: 'parmigiano reggiano', label: 'parmigiano reggiano' },
    { value: 'shredded cheese', label: 'shredded cheese' },
    { value: 'dal', label: 'dal' },
    { value: 'chicken thighs', label: 'chicken thighs' },
    { value: 'baby carrots', label: 'baby carrots' },
    { value: 'flank steak', label: 'flank steak' },
    { value: 'dried apricots', label: 'dried apricots' },
    { value: 'confectioners sugar', label: 'confectioners sugar' },
    { value: 'cheddar', label: 'cheddar' },
    { value: 'vegan cheese', label: 'vegan cheese' },
    { value: 'yellow mustard', label: 'yellow mustard' },
    { value: 'extra-virgin olive oil', label: 'extra-virgin olive oil' },
    { value: 'oregano leaves', label: 'oregano leaves' },
    { value: 'dried coriander leaves', label: 'dried coriander leaves' },
    { value: 'cajun seasoning', label: 'cajun seasoning' },
    { value: 'ranch dressing', label: 'ranch dressing' },
    { value: 'oyster sauce', label: 'oyster sauce' },
    { value: 'sun-dried tomatoes', label: 'sun-dried tomatoes' },
    { value: 'dry sherry', label: 'dry sherry' },
    { value: 'lettuce leaves', label: 'lettuce leaves' },
    { value: 'full-fat milk', label: 'full-fat milk' },
    { value: 'gruyere cheese', label: 'gruyere cheese' },
    { value: 'dry bread crumbs', label: 'dry bread crumbs' },
    { value: 'coarse sea salt', label: 'coarse sea salt' },
    { value: 'rice flour', label: 'rice flour' },
    { value: 'fresh tarragon', label: 'fresh tarragon' },
    { value: 'semi-sweet chocolate', label: 'semi-sweet chocolate' },
    { value: 'white bread', label: 'white bread' },
    { value: 'roast beef', label: 'roast beef' },
    { value: 'juice', label: 'juice' },
    { value: 'white whole wheat flour', label: 'white whole wheat flour' },
    { value: 'low fat sour cream', label: 'low fat sour cream' },
    { value: 'chillies', label: 'chillies' },
    { value: 'instant yeast', label: 'instant yeast' },
    { value: 'pineapple chunks', label: 'pineapple chunks' },
    { value: 'condensed cream of mushroom soup', label: 'condensed cream of mushroom soup' },
    { value: 'mirin', label: 'mirin' },
    { value: 'roasted peanuts', label: 'roasted peanuts' },
    { value: 'snow peas', label: 'snow peas' },
    { value: 'yellow cake mix', label: 'yellow cake mix' },
    { value: 'sub rolls', label: 'sub rolls' },
    { value: 'yellow squash', label: 'yellow squash' },
    { value: 'almond', label: 'almond' },
    { value: 'herbs', label: 'herbs' },
    { value: 'maraschino cherries', label: 'maraschino cherries' },
    { value: 'cremini mushrooms', label: 'cremini mushrooms' },
    { value: 'meat', label: 'meat' },
    { value: 'white distilled vinegar', label: 'white distilled vinegar' },
    { value: 'italian sausage', label: 'italian sausage' },
    { value: 'mozzarella', label: 'mozzarella' },
    { value: 'fat-free less-sodium chicken broth', label: 'fat-free less-sodium chicken broth' },
    { value: 'dark rum', label: 'dark rum' },
    { value: 'pizza dough', label: 'pizza dough' },
    { value: 'milk chocolate chips', label: 'milk chocolate chips' },
    { value: 'peppercorns', label: 'peppercorns' },
    { value: 'penne pasta', label: 'penne pasta' },
    { value: 'cooked ham', label: 'cooked ham' },
    { value: 'chicken wings', label: 'chicken wings' },
    { value: 'peppermint extract', label: 'peppermint extract' },
    { value: 'swerve sweetener', label: 'swerve sweetener' },
    { value: 'cottage cheese', label: 'cottage cheese' },
    { value: 'golden brown sugar', label: 'golden brown sugar' },
    { value: 'egg noodles', label: 'egg noodles' },
    { value: 'parsnips', label: 'parsnips' },
    { value: 'grapeseed oil', label: 'grapeseed oil' },
    { value: 'mascarpone cheese', label: 'mascarpone cheese' },
    { value: 'dessert wine', label: 'dessert wine' },
    { value: 'baby spinach leaves', label: 'baby spinach leaves' },
    { value: 'baking potatoes', label: 'baking potatoes' },
    { value: 'avocado oil', label: 'avocado oil' },
    { value: 'salad dressing', label: 'salad dressing' },
    { value: 'parmigiano reggiano cheese', label: 'parmigiano reggiano cheese' },
    { value: 'star anise', label: 'star anise' },
    { value: 'green cabbage', label: 'green cabbage' },
    { value: 'thick-cut bacon', label: 'thick-cut bacon' },
    { value: 'pumpkin seeds', label: 'pumpkin seeds' },
    { value: 'coriander powder', label: 'coriander powder' },
    { value: 'juice of orange', label: 'juice of orange' },
    { value: 'basmati rice', label: 'basmati rice' },
    { value: 'granny smith apple', label: 'granny smith apple' },
    { value: 'whole wheat pastry flour', label: 'whole wheat pastry flour' },
    { value: 'old fashioned rolled oats', label: 'old fashioned rolled oats' },
    { value: 'caramel sauce', label: 'caramel sauce' },
    { value: 'shiitake mushrooms', label: 'shiitake mushrooms' },
    { value: 'dairy milk', label: 'dairy milk' },
    { value: 'baking bar', label: 'baking bar' },
    { value: 'chilies', label: 'chilies' },
    { value: 'iceberg lettuce', label: 'iceberg lettuce' },
    { value: 'sage', label: 'sage' },
    { value: 'elbow macaroni', label: 'elbow macaroni' },
    { value: 'tea', label: 'tea' },
    { value: 'red beans', label: 'red beans' },
    { value: 'lemongrass', label: 'lemongrass' },
    { value: 'spaghetti sauce', label: 'spaghetti sauce' },
    { value: 'cardamom', label: 'cardamom' },
    { value: 'bacon strips', label: 'bacon strips' },
    { value: 'old-fashioned oats', label: 'old-fashioned oats' },
    { value: 'arborio rice', label: 'arborio rice' },
    { value: 'greens', label: 'greens' },
    { value: 'm&m candy', label: 'm&m candy' },
    { value: 'panko breadcrumbs', label: 'panko breadcrumbs' },
    { value: 'baby-back ribs', label: 'baby-back ribs' },
    { value: 'saffron', label: 'saffron' },
    { value: 'whole eggs', label: 'whole eggs' },
    { value: 'spinach leaves', label: 'spinach leaves' },
    { value: 'seafood stock', label: 'seafood stock' },
    { value: 'pretzels', label: 'pretzels' },
    { value: 'medjool dates', label: 'medjool dates' },
    { value: 'sunflower oil', label: 'sunflower oil' },
    { value: 'pepper jack cheese', label: 'pepper jack cheese' },
    { value: 'oatmeal', label: 'oatmeal' },
    { value: 'coconut cream', label: 'coconut cream' },
    { value: 'oat flour', label: 'oat flour' },
    { value: 'shredded mexican cheese blend', label: 'shredded mexican cheese blend' },
    { value: 'sweet paprika', label: 'sweet paprika' },
    { value: 'cranberry juice', label: 'cranberry juice' },
    { value: 'noodles', label: 'noodles' },
    { value: 'sheeps milk cheese', label: 'sheeps milk cheese' },
    { value: 'pasta sauce', label: 'pasta sauce' },
    { value: 'cane sugar', label: 'cane sugar' },
    { value: 'tortillas', label: 'tortillas' },
    { value: 'asparagus spears', label: 'asparagus spears' },
    { value: 'cream of mushroom soup', label: 'cream of mushroom soup' },
    { value: 'fresh green beans', label: 'fresh green beans' },
    { value: 'maca powder', label: 'maca powder' },
    { value: 'nutella', label: 'nutella' },
    { value: 'double cream', label: 'double cream' },
    { value: 'chorizo', label: 'chorizo' },
    { value: 'ground chicken', label: 'ground chicken' },
    { value: 'cumin powder', label: 'cumin powder' },
    { value: 'couscous', label: 'couscous' },
    { value: 'gluten-free flour', label: 'gluten-free flour' },
    { value: 'canned corn', label: 'canned corn' },
    { value: 'whole chicken', label: 'whole chicken' },
    { value: 'green olives', label: 'green olives' },
    { value: 'tomato soup', label: 'tomato soup' },
    { value: 'asafoetida', label: 'asafoetida' },
    { value: 'red food coloring', label: 'red food coloring' },
    { value: 'brownie mix', label: 'brownie mix' },
    { value: 'condensed cream of chicken soup', label: 'condensed cream of chicken soup' },
    { value: 'light soy sauce', label: 'light soy sauce' },
    { value: 'celery seed', label: 'celery seed' },
    { value: 'unsweetened cocoa', label: 'unsweetened cocoa' },
    { value: 'watercress', label: 'watercress' },
    { value: 'crackers', label: 'crackers' },
    { value: 'sweetened coconut', label: 'sweetened coconut' },
    { value: 'cup cake', label: 'cup cake' },
    { value: 'raw cashews', label: 'raw cashews' },
    { value: 'cauliflower florets', label: 'cauliflower florets' },
    { value: 'sugar snap peas', label: 'sugar snap peas' },
    { value: 'poultry seasoning', label: 'poultry seasoning' },
    { value: 'baby arugula', label: 'baby arugula' },
    { value: 'bean sprouts', label: 'bean sprouts' },
    { value: 'lb cake', label: 'lb cake' },
    { value: 'whole kernel corn', label: 'whole kernel corn' },
    { value: 'spaghetti squash', label: 'spaghetti squash' },
    { value: 'tomatillos', label: 'tomatillos' },
    { value: 'eggplants', label: 'eggplants' },
    { value: 'strong coffee', label: 'strong coffee' },
    { value: 'old fashioned oats', label: 'old fashioned oats' },
    { value: 'cooked brown rice', label: 'cooked brown rice' },
    { value: 'pizza mix', label: 'pizza mix' },
    { value: 'dried cherries', label: 'dried cherries' },
    { value: 'paneer', label: 'paneer' },
    { value: 'rice noodles', label: 'rice noodles' },
    { value: 'light coconut milk', label: 'light coconut milk' },
    { value: 'red grapes', label: 'red grapes' },
    { value: 'refried beans', label: 'refried beans' },
    { value: 'swiss chard', label: 'swiss chard' },
    { value: 'raw honey', label: 'raw honey' },
    { value: 'orange marmalade', label: 'orange marmalade' },
    { value: 'beef stew meat', label: 'beef stew meat' },
    { value: 'fresh corn kernels', label: 'fresh corn kernels' },
    { value: 'mustard powder', label: 'mustard powder' },
    { value: 'panko', label: 'panko' },
    { value: 'tomato juice', label: 'tomato juice' },
    { value: 'napa cabbage', label: 'napa cabbage' },
    { value: 'instant chocolate pudding mix', label: 'instant chocolate pudding mix' },
    { value: 'oreo cookies', label: 'oreo cookies' },
    { value: 'chiles', label: 'chiles' },
    { value: 'whiskey', label: 'whiskey' },
    { value: 'extra firm tofu', label: 'extra firm tofu' },
    { value: 'new potatoes', label: 'new potatoes' },
    { value: 'cereal', label: 'cereal' },
    { value: 'pink himalayan salt', label: 'pink himalayan salt' },
    { value: 'cookie', label: 'cookie' },
    { value: 'mussels', label: 'mussels' },
    { value: 'half n half cream', label: 'half n half cream' },
    { value: 'hummus', label: 'hummus' },
    { value: 'light mayonnaise', label: 'light mayonnaise' },
    { value: 'carp', label: 'carp' },
    { value: 'lentils', label: 'lentils' },
    { value: 'tapioca flour', label: 'tapioca flour' },
    { value: 'taco seasoning mix', label: 'taco seasoning mix' },
    { value: 'cornflour', label: 'cornflour' },
    { value: 'linguine', label: 'linguine' },
    { value: 'gin', label: 'gin' },
    { value: 'deli ham', label: 'deli ham' },
    { value: 'coarse kosher salt', label: 'coarse kosher salt' },
    { value: 'corn chips', label: 'corn chips' },
    { value: 'fontina cheese', label: 'fontina cheese' },
    { value: 'vegetarian bacon', label: 'vegetarian bacon' },
    { value: 'okra', label: 'okra' },
    { value: 'almond meal', label: 'almond meal' },
    { value: 'low-salt chicken broth', label: 'low-salt chicken broth' },
    { value: 'celery salt', label: 'celery salt' },
    { value: 'rotisserie chicken', label: 'rotisserie chicken' },
    { value: 'nonfat greek yogurt', label: 'nonfat greek yogurt' },
    { value: 'unsweetened coconut milk', label: 'unsweetened coconut milk' },
    { value: 'baking cocoa', label: 'baking cocoa' },
    { value: 'pasta salad mix', label: 'pasta salad mix' },
    { value: 'flat leaf parsley leaves', label: 'flat leaf parsley leaves' },
    { value: 'live lobster', label: 'live lobster' },
    { value: 'green peas', label: 'green peas' },
    { value: 'pizza crust', label: 'pizza crust' },
    { value: 'edamame', label: 'edamame' },
    { value: 'stock', label: 'stock' },
    { value: 'broth', label: 'broth' },
    { value: 'pork loin chops', label: 'pork loin chops' },
    { value: 'turkey breast', label: 'turkey breast' },
    { value: 'fennel', label: 'fennel' },
    { value: 'caraway seeds', label: 'caraway seeds' },
    { value: 'orange rind', label: 'orange rind' },
    { value: 'canned pinto beans', label: 'canned pinto beans' },
    { value: 'lean ground turkey', label: 'lean ground turkey' },
    { value: 'romano cheese', label: 'romano cheese' },
    { value: 'lamb', label: 'lamb' },
    { value: 'celery stalk', label: 'celery stalk' },
    { value: 'chocolate syrup', label: 'chocolate syrup' },
    { value: 'canned cannellini beans', label: 'canned cannellini beans' },
    { value: 'pomegranate seeds', label: 'pomegranate seeds' },
    { value: 'shredded mozzarella', label: 'shredded mozzarella' },
    { value: 'self-rising flour', label: 'self-rising flour' },
    { value: 'tabasco sauce', label: 'tabasco sauce' },
    { value: 'caramel', label: 'caramel' },
    { value: 'biscuits', label: 'biscuits' },
    { value: 'macadamia nuts', label: 'macadamia nuts' },
    { value: 'steak', label: 'steak' },
    { value: 'enchilada sauce', label: 'enchilada sauce' },
    { value: 'dark sesame oil', label: 'dark sesame oil' },
    { value: 'spring onion', label: 'spring onion' },
    { value: 'anchovy', label: 'anchovy' },
    { value: 'rice paper', label: 'rice paper' },
    { value: 'guacamole', label: 'guacamole' },
    { value: 'smoked salmon', label: 'smoked salmon' },
    { value: 'salad greens', label: 'salad greens' },
    { value: 'beef chuck roast', label: 'beef chuck roast' },
    { value: 'egg substitute', label: 'egg substitute' },
    { value: 'lasagna noodles', label: 'lasagna noodles' },
    { value: 'fresh ginger root', label: 'fresh ginger root' },
    { value: 'grapes', label: 'grapes' },
    { value: 'sourdough bread', label: 'sourdough bread' },
    { value: 'dry roasted peanuts', label: 'dry roasted peanuts' },
    { value: 'strawberry', label: 'strawberry' },
    { value: 'seeds', label: 'seeds' },
    { value: 'raspberry jam', label: 'raspberry jam' },
    { value: 'cacao powder', label: 'cacao powder' },
    { value: 'lemon extract', label: 'lemon extract' },
    { value: 'breakfast syrup', label: 'breakfast syrup' },
    { value: 'apricots', label: 'apricots' },
    { value: 'apricot preserves', label: 'apricot preserves' },
    { value: 'salmon fillet', label: 'salmon fillet' },
    { value: 'granola', label: 'granola' },
    { value: 'baby potatoes', label: 'baby potatoes' },
    { value: 'sharp cheddar', label: 'sharp cheddar' },
    { value: 'onion soup mix', label: 'onion soup mix' },
    { value: 'diced ham', label: 'diced ham' },
    { value: 'erythritol', label: 'erythritol' },
    { value: 'fresh sage leaves', label: 'fresh sage leaves' },
    { value: 'american cheese', label: 'american cheese' },
    { value: 'potato starch', label: 'potato starch' },
    { value: 'low fat cream cheese', label: 'low fat cream cheese' },
    { value: 'instant vanilla pudding mix', label: 'instant vanilla pudding mix' },
    { value: 'crusty bread', label: 'crusty bread' },
    { value: 'canned garbanzo beans', label: 'canned garbanzo beans' },
    { value: 'chilli', label: 'chilli' },
    { value: 'gf chocolate cake mix', label: 'gf chocolate cake mix' },
    { value: 'popcorn', label: 'popcorn' },
    { value: 'halloween sprinkles', label: 'halloween sprinkles' },
    { value: 'sherry', label: 'sherry' },
    { value: 'vegetable', label: 'vegetable' },
    { value: 'saffron threads', label: 'saffron threads' },
    { value: 'cherry', label: 'cherry' },
    { value: 'figs', label: 'figs' },
    { value: 'curry paste', label: 'curry paste' },
    { value: 'icing', label: 'icing' },
    { value: 'low fat mayonnaise', label: 'low fat mayonnaise' },
    { value: 'dried onion', label: 'dried onion' },
    { value: 'red pepper powder', label: 'red pepper powder' },
    { value: 'orange juice concentrate', label: 'orange juice concentrate' },
    { value: 'paleo wrap', label: 'paleo wrap' },
    { value: 'baby bella mushrooms', label: 'baby bella mushrooms' },
    { value: 'great northern beans', label: 'great northern beans' },
    { value: 'clams', label: 'clams' },
    { value: 'seasoning salt', label: 'seasoning salt' },
    { value: 'ground almonds', label: 'ground almonds' },
    { value: 'full fat coconut milk', label: 'full fat coconut milk' },
    { value: 'ready to use piecrust', label: 'ready to use piecrust' },
    { value: 'chocolate chip cookies', label: 'chocolate chip cookies' },
    { value: 'ginger root', label: 'ginger root' },
    { value: 'italian dressing', label: 'italian dressing' },
    { value: 'low fat buttermilk', label: 'low fat buttermilk' },
    { value: 'cupcakes', label: 'cupcakes' },
    { value: 'jam', label: 'jam' },
    { value: 'coconut aminos', label: 'coconut aminos' },
    { value: 'adobo sauce', label: 'adobo sauce' },
    { value: 'canned beef broth', label: 'canned beef broth' },
    { value: 'cooked white rice', label: 'cooked white rice' },
    { value: 'dark chocolate candy bars', label: 'dark chocolate candy bars' },
    { value: 'nonfat milk', label: 'nonfat milk' },
    { value: 'whole wheat bread', label: 'whole wheat bread' },
    { value: 'sweetened shredded coconut', label: 'sweetened shredded coconut' },
    { value: 'teriyaki sauce', label: 'teriyaki sauce' },
    { value: 'rice wine', label: 'rice wine' },
    { value: 'polenta', label: 'polenta' },
    { value: 'green bell peppers', label: 'green bell peppers' },
    { value: 'fresh mozzarella', label: 'fresh mozzarella' },
    { value: 'dried sage', label: 'dried sage' },
    { value: 'dried parsley flakes', label: 'dried parsley flakes' },
    { value: 'baby dill', label: 'baby dill' },
    { value: 'urad dal', label: 'urad dal' },
    { value: 'dinner rolls', label: 'dinner rolls' },
    { value: 'condensed milk', label: 'condensed milk' },
    { value: 'steel cut oats', label: 'steel cut oats' },
    { value: 'tuna', label: 'tuna' },
    { value: 'tart apples', label: 'tart apples' },
    { value: 'blanched almonds', label: 'blanched almonds' },
    { value: 'sake', label: 'sake' },
    { value: 'low-fat cream cheese', label: 'low-fat cream cheese' },
    { value: 'turbinado sugar', label: 'turbinado sugar' },
    { value: 'green chilli', label: 'green chilli' },
    { value: 'sauerkraut', label: 'sauerkraut' },
    { value: 'vanilla yogurt', label: 'vanilla yogurt' },
    { value: 'cherry pie filling', label: 'cherry pie filling' },
    { value: 'crystallized ginger', label: 'crystallized ginger' },
    { value: 'wonton wrappers', label: 'wonton wrappers' },
    { value: 'Dairy Free Cheese', label: 'Dairy Free Cheese' },
    { value: 'baked beans', label: 'baked beans' },
    { value: 'tamari', label: 'tamari' },
    { value: 'tarragon', label: 'tarragon' },
    { value: 'sage leaves', label: 'sage leaves' },
    { value: 'dry yeast', label: 'dry yeast' },
    { value: 'acorn squash', label: 'acorn squash' },
    { value: 'canned water chestnuts', label: 'canned water chestnuts' },
    { value: 'date', label: 'date' },
    { value: 'plums', label: 'plums' },
    { value: 'roasted red pepper', label: 'roasted red pepper' },
    { value: 'pork belly', label: 'pork belly' },
    { value: 'cheese curds', label: 'cheese curds' },
    { value: 'basil pesto', label: 'basil pesto' },
    { value: 'hard-boiled eggs', label: 'hard-boiled eggs' },
    { value: 'triple sec', label: 'triple sec' },
    { value: 'mangoes', label: 'mangoes' },
    { value: 'smooth peanut butter', label: 'smooth peanut butter' },
    { value: 'rajma masala', label: 'rajma masala' },
    { value: 'hard cooked eggs', label: 'hard cooked eggs' },
    { value: 'apple pie spice', label: 'apple pie spice' },
    { value: 'wheat germ', label: 'wheat germ' },
    { value: 'fresh coriander', label: 'fresh coriander' },
    { value: 'pomegranate juice', label: 'pomegranate juice' },
    { value: 'chili paste', label: 'chili paste' },
    { value: 'all-purpose flour', label: 'all-purpose flour' },
    { value: 'low sodium chicken stock', label: 'low sodium chicken stock' },
    { value: 'red peppers', label: 'red peppers' },
    { value: 'toast', label: 'toast' },
    { value: 'pimento stuffed olives', label: 'pimento stuffed olives' },
    { value: 'ground cayenne pepper', label: 'ground cayenne pepper' },
    { value: 'sea scallops', label: 'sea scallops' },
    { value: 'salami', label: 'salami' },
    { value: 'chile powder', label: 'chile powder' },
    { value: 'dill weed', label: 'dill weed' },
    { value: 'asiago cheese', label: 'asiago cheese' },
    { value: 'slaw dressing', label: 'slaw dressing' },
    { value: 'white balsamic vinegar', label: 'white balsamic vinegar' },
    { value: 'fresh rosemary leaves', label: 'fresh rosemary leaves' },
    { value: 'granulated garlic', label: 'granulated garlic' },
    { value: 'ricotta', label: 'ricotta' },
    { value: 'whole cranberry sauce', label: 'whole cranberry sauce' },
    { value: 'low fat plain yogurt', label: 'low fat plain yogurt' },
    { value: 'chicken breast halves', label: 'chicken breast halves' },
    { value: 'red chilli', label: 'red chilli' },
    { value: 'radicchio', label: 'radicchio' },
    { value: 'cantaloupe', label: 'cantaloupe' },
    { value: 'canned tuna', label: 'canned tuna' },
    { value: 'portobello mushrooms', label: 'portobello mushrooms' },
    { value: 'soy milk', label: 'soy milk' },
    { value: 'vanilla bean paste', label: 'vanilla bean paste' },
    { value: 'instant coffee granules', label: 'instant coffee granules' },
    { value: 'spicy brown mustard', label: 'spicy brown mustard' },
    { value: 'turnips', label: 'turnips' },
    { value: 'white mushrooms', label: 'white mushrooms' },
    { value: 'milk chocolate', label: 'milk chocolate' },
    { value: 'processed american cheese', label: 'processed american cheese' },
    { value: 'pork links', label: 'pork links' },
    { value: 'brown rice flour', label: 'brown rice flour' },
    { value: 'round steak', label: 'round steak' },
    { value: 'clam juice', label: 'clam juice' },
    { value: 'chocolate milk', label: 'chocolate milk' },
    { value: 'champagne vinegar', label: 'champagne vinegar' },
    { value: 'coleslaw mix', label: 'coleslaw mix' },
    { value: 'green chiles', label: 'green chiles' },
    { value: 'meatballs', label: 'meatballs' },
    { value: 'dried marjoram', label: 'dried marjoram' },
    { value: 'coconut extract', label: 'coconut extract' },
    { value: 'jicama', label: 'jicama' },
    { value: 'grapefruit', label: 'grapefruit' },
    { value: 'peanut butter cups', label: 'peanut butter cups' },
    { value: 'chili flakes', label: 'chili flakes' },
    { value: 'lump crabmeat', label: 'lump crabmeat' },
    { value: 'sriracha sauce', label: 'sriracha sauce' },
    { value: 'raw shrimp', label: 'raw shrimp' },
    { value: 'old bay seasoning', label: 'old bay seasoning' },
    { value: 'game', label: 'game' },
    { value: 'caramels', label: 'caramels' },
    { value: 'jack cheese', label: 'jack cheese' },
    { value: 'seasoned bread crumbs', label: 'seasoned bread crumbs' },
    { value: 'italian bread', label: 'italian bread' },
    { value: 'cardamom pods', label: 'cardamom pods' },
    { value: 'mix of brownies', label: 'mix of brownies' },
    { value: 'artichokes', label: 'artichokes' },
    { value: 'rice syrup', label: 'rice syrup' },
    { value: 'capsicum', label: 'capsicum' },
    { value: 'plum tomato', label: 'plum tomato' },
    { value: 'fresh herbs', label: 'fresh herbs' },
    { value: 'tapioca starch', label: 'tapioca starch' },
    { value: 'orange bell pepper', label: 'orange bell pepper' },
    { value: 'coconut butter', label: 'coconut butter' },
    { value: 'creole seasoning', label: 'creole seasoning' },
    { value: 'canned green chiles', label: 'canned green chiles' },
    { value: 'Spice Rub', label: 'Spice Rub' },
    { value: 'tea bags', label: 'tea bags' },
    { value: 'instant vanilla pudding', label: 'instant vanilla pudding' },
    { value: 'cheese soup', label: 'cheese soup' },
    { value: 'leg of lamb', label: 'leg of lamb' },
    { value: 'diet pop', label: 'diet pop' },
    { value: 'green peppers', label: 'green peppers' },
    { value: 'long grain rice', label: 'long grain rice' },
    { value: 'lemon pepper', label: 'lemon pepper' },
    { value: 'beef brisket', label: 'beef brisket' },
    { value: 'baking chocolate', label: 'baking chocolate' },
    { value: 'pork sausage', label: 'pork sausage' },
    { value: 'beet', label: 'beet' },
    { value: 'cardamom powder', label: 'cardamom powder' },
    { value: 'gingerbread kids', label: 'gingerbread kids' },
    { value: 'white flour', label: 'white flour' },
    { value: 'grand marnier', label: 'grand marnier' },
    { value: 'chocolate ice cream', label: 'chocolate ice cream' },
    { value: 'low fat shredded cheddar cheese', label: 'low fat shredded cheddar cheese' },
    { value: 'fettuccine', label: 'fettuccine' },
    { value: 'canned mandarin oranges', label: 'canned mandarin oranges' },
    { value: 'instant espresso powder', label: 'instant espresso powder' },
    { value: 'corn kernel', label: 'corn kernel' },
    { value: 'tea bag', label: 'tea bag' },
    { value: 'queso fresco', label: 'queso fresco' },
    { value: 'croutons', label: 'croutons' },
    { value: 'frosting', label: 'frosting' },
    { value: 'roasted pork', label: 'roasted pork' },
    { value: 'fleur de sel', label: 'fleur de sel' },
    { value: 'ginger ale', label: 'ginger ale' },
    { value: 'blanched almond flour', label: 'blanched almond flour' },
    { value: 'pretzel sandwiches', label: 'pretzel sandwiches' },
    { value: 'multi-grain bread', label: 'multi-grain bread' },
    { value: 'crisp rice cereal', label: 'crisp rice cereal' },
    { value: '5 spice powder', label: '5 spice powder' },
    { value: 'thai red curry paste', label: 'thai red curry paste' },
    { value: 'prawns', label: 'prawns' },
    { value: 'marshmallow creme', label: 'marshmallow creme' },
    { value: 'champagne', label: 'champagne' },
    { value: 'wheat flour', label: 'wheat flour' },
    { value: 'pumpkin spice mix', label: 'pumpkin spice mix' },
    { value: 'salsa verde', label: 'salsa verde' },
    { value: 'italian cheese blend', label: 'italian cheese blend' },
    { value: 'winter squash', label: 'winter squash' },
    { value: 'macaroni dinner', label: 'macaroni dinner' },
    { value: 'orange liqueur', label: 'orange liqueur' },
    { value: 'pearl onions', label: 'pearl onions' },
    { value: 'full-fat coconut milk', label: 'full-fat coconut milk' },
    { value: 'dry breadcrumbs', label: 'dry breadcrumbs' },
    { value: 'Top Sirloin', label: 'Top Sirloin' },
    { value: 'ground flaxseed', label: 'ground flaxseed' },
    { value: 'yellow bell peppers', label: 'yellow bell peppers' },
    { value: 'steaks', label: 'steaks' },
    { value: 'roma tomato', label: 'roma tomato' },
    { value: 'marinated artichoke hearts', label: 'marinated artichoke hearts' },
    { value: 'coconut flakes', label: 'coconut flakes' },
    { value: 'low sodium beef broth', label: 'low sodium beef broth' },
    { value: 'candy melts', label: 'candy melts' },
    { value: 'liquid stevia', label: 'liquid stevia' },
    { value: 'bamboo shoots', label: 'bamboo shoots' },
    { value: 'cod', label: 'cod' },
    { value: 'chocolate chip cookie', label: 'chocolate chip cookie' },
    { value: 'squash', label: 'squash' },
    { value: 'bok choy', label: 'bok choy' },
    { value: 'angel food cake mix', label: 'angel food cake mix' },
    { value: 'canned white beans', label: 'canned white beans' },
    { value: 'spring mix', label: 'spring mix' },
    { value: 'butterscotch chips', label: 'butterscotch chips' },
    { value: 'hot dogs', label: 'hot dogs' },
    { value: 'instant coffee', label: 'instant coffee' },
    { value: 'fried onions', label: 'fried onions' },
    { value: 'eggnog', label: 'eggnog' },
    { value: 'pound cake', label: 'pound cake' },
    { value: 'dried tarragon', label: 'dried tarragon' },
    { value: 'natural sugar', label: 'natural sugar' },
    { value: 'queso dip', label: 'queso dip' },
    { value: 'canned mushrooms', label: 'canned mushrooms' },
    { value: 'peanut butter chips', label: 'peanut butter chips' },
    { value: 'filo pastry', label: 'filo pastry' },
    { value: 'ground lamb', label: 'ground lamb' },
    { value: 'self-raising flour', label: 'self-raising flour' },
    { value: 'fresh peas', label: 'fresh peas' },
    { value: 'phyllo dough', label: 'phyllo dough' },
    { value: 'chicken tenders', label: 'chicken tenders' },
    { value: 'vanilla frosting', label: 'vanilla frosting' },
    { value: 'grapefruit juice', label: 'grapefruit juice' },
    { value: 'lime peel', label: 'lime peel' },
    { value: 'pork loin', label: 'pork loin' },
    { value: 'balsamic glaze', label: 'balsamic glaze' },
    { value: 'dried porcini mushrooms', label: 'dried porcini mushrooms' },
    { value: 'red sweet pepper', label: 'red sweet pepper' },
    { value: 'sun dried tomatoes', label: 'sun dried tomatoes' },
    { value: 'ground sausage', label: 'ground sausage' },
    { value: 'raw sugar', label: 'raw sugar' },
    { value: 'graham cracker crust', label: 'graham cracker crust' },
    { value: 'vegetable oils', label: 'vegetable oils' },
    { value: 'stuffing mix', label: 'stuffing mix' },
    { value: 'real cheese', label: 'real cheese' },
    { value: 'top blade steak', label: 'top blade steak' },
    { value: 'cloves', label: 'cloves' },
    { value: 'chocolate cookies', label: 'chocolate cookies' },
    { value: 'black sesame seeds', label: 'black sesame seeds' },
    { value: 'food color', label: 'food color' },
    { value: 'red lentils', label: 'red lentils' },
    { value: 'hemp seeds', label: 'hemp seeds' },
    { value: 'hash brown potatoes', label: 'hash brown potatoes' },
    { value: 'red chili powder', label: 'red chili powder' },
    { value: 'tomato ketchup', label: 'tomato ketchup' },
    { value: 'cinnamon sugar', label: 'cinnamon sugar' },
    { value: 'jumbo shrimp', label: 'jumbo shrimp' },
    { value: 'chipotle peppers in adobo', label: 'chipotle peppers in adobo' },
    { value: 'thai basil', label: 'thai basil' },
    { value: 'serrano chile', label: 'serrano chile' },
    { value: 'grain blend', label: 'grain blend' },
    { value: 'silken tofu', label: 'silken tofu' },
    { value: 'roasted red bell peppers', label: 'roasted red bell peppers' },
    { value: 'red curry paste', label: 'red curry paste' },
    { value: 'toffee bits', label: 'toffee bits' },
    { value: 'green food coloring', label: 'green food coloring' },
    { value: 'chili pepper', label: 'chili pepper' },
    { value: 'fennel seed', label: 'fennel seed' },
    { value: 'chile paste', label: 'chile paste' },
    { value: 'gingerroot', label: 'gingerroot' },
    { value: 'english muffins', label: 'english muffins' },
    { value: 'wild rice', label: 'wild rice' },
    { value: 'honey mustard', label: 'honey mustard' },
    { value: 'dried dill', label: 'dried dill' },
    { value: 'cream cheese block', label: 'cream cheese block' },
    { value: 'pecorino romano cheese', label: 'pecorino romano cheese' },
    { value: 'fresh corn', label: 'fresh corn' },
    { value: 'chicken bouillon granules', label: 'chicken bouillon granules' },
    { value: 'vine ripened tomatoes', label: 'vine ripened tomatoes' },
    { value: 'minute rice', label: 'minute rice' },
    { value: 'marjoram', label: 'marjoram' },
    { value: 'ranch dressing mix', label: 'ranch dressing mix' },
    { value: 'salted peanuts', label: 'salted peanuts' },
    { value: 'white sandwich bread', label: 'white sandwich bread' },
    { value: 'sub buns', label: 'sub buns' },
    { value: 'instant brown rice', label: 'instant brown rice' },
    { value: 'fresh gingerroot', label: 'fresh gingerroot' },
    { value: 'brie', label: 'brie' },
    { value: 'ears of corn', label: 'ears of corn' },
    { value: 'brie cheese', label: 'brie cheese' },
    { value: 'pork shoulder', label: 'pork shoulder' },
    { value: 'herbes de provence', label: 'herbes de provence' },
    { value: 'walnut halves', label: 'walnut halves' },
    { value: 'pb cups', label: 'pb cups' },
    { value: 'duck fat', label: 'duck fat' },
    { value: 'jasmine rice', label: 'jasmine rice' },
    { value: 'bacon bits', label: 'bacon bits' },
    { value: 'solid pack pumpkin', label: 'solid pack pumpkin' },
    { value: 'oreos', label: 'oreos' },
    { value: 'coconut water', label: 'coconut water' },
    { value: 'cotija cheese', label: 'cotija cheese' },
    { value: 'mint chutney', label: 'mint chutney' },
    { value: 'ready-to-serve Asian fried rice', label: 'ready-to-serve Asian fried rice' },
    { value: 'angel hair pasta', label: 'angel hair pasta' },
    { value: 'strawberry jam', label: 'strawberry jam' },
    { value: 'whole egg', label: 'whole egg' },
    { value: 'sweet onions', label: 'sweet onions' },
    { value: 'corn flour', label: 'corn flour' },
    { value: 'vanilla wafers', label: 'vanilla wafers' },
    { value: 'cod fillets', label: 'cod fillets' },
    { value: 'beef top sirloin steak', label: 'beef top sirloin steak' },
    { value: 'apricot jam', label: 'apricot jam' },
    { value: 'romaine', label: 'romaine' },
    { value: 'quinoa flour', label: 'quinoa flour' },
    { value: 'rum extract', label: 'rum extract' },
    { value: 'vanilla protein powder', label: 'vanilla protein powder' },
    { value: 'flaxseed meal', label: 'flaxseed meal' },
    { value: 'pesto sauces', label: 'pesto sauces' },
    { value: 'rye bread', label: 'rye bread' },
    { value: 'cannellini beans', label: 'cannellini beans' },
    { value: 'scallops', label: 'scallops' },
    { value: 'froyo bars', label: 'froyo bars' },
    { value: 'bread bowl', label: 'bread bowl' },
    { value: 'gorgonzola cheese', label: 'gorgonzola cheese' },
    { value: 'Miso Soybean Paste', label: 'Miso Soybean Paste' },
    { value: 'bulk pork sausage', label: 'bulk pork sausage' },
    { value: 'corn oil', label: 'corn oil' },
    { value: 'mixed veggies', label: 'mixed veggies' },
    { value: 'vanilla essence', label: 'vanilla essence' },
    { value: 'prunes', label: 'prunes' },
    { value: 'plain nonfat yogurt', label: 'plain nonfat yogurt' },
    { value: 'chicken drumsticks', label: 'chicken drumsticks' },
    { value: 'pear liqueur', label: 'pear liqueur' },
    { value: 'chive & onion cream cheese spread', label: 'chive & onion cream cheese spread' },
    { value: 'espresso powder', label: 'espresso powder' },
    { value: 'gingerbread people', label: 'gingerbread people' },
    { value: 'unsweetened coconut flakes', label: 'unsweetened coconut flakes' },
    { value: 'dried currants', label: 'dried currants' },
];

function Ingredients() {
    const navigate = useNavigate();
    const [selected, setSelected] = useState([])
    const [input, setInput] = useState("")

    const HandleChange = (event, updatedType) => {
        let temp = '';
        event.forEach(item => {
            temp += item['value'] + '+'
        });
        setSelected(event);
        setInput(temp.substring(0, temp.length - 1).replace(' ', '-'))
    }

    const handleSubmit = (e) => {
        e.preventDefault();
        navigate("/searched+ingredient/" + input);
    };

    return (
        <>
        <div className='Select'>
            <Select
                value={selected}
                onChange={HandleChange}
                isMulti
                isSearchable
                options={options} 
                closeMenuOnSelect={false}
            />
        </div>
        <div className='searchbutton'>
            <button type="button" className="btn btn-primary" onClick={handleSubmit}>Seach</button>
        </div>
        
        </>
    )
}

export default Ingredients;